
# This file was generated by 'versioning.py' from revision-control system
# data, or from the parent directory name of an unpacked source archive.
# Distribution tarballs contain a pre-generated copy of this file.

__version__ = '0.4'
