name: CI

on:
  push:
  pull_request:

jobs:
  test-install:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [2.7, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, "3.10", 3.11-dev, pypy-2.7, pypy-3.6, pypy-3.7, pypy-3.8]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.4.0

      - name: Setup python
        uses: actions/setup-python@v2.3.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test Installation
        run: |
          python setup.py build
          python setup.py test
          python setup.py test_kat
          python setup.py speed
